name: Build Vote Service

on:
  push:
    branches:
      - 'main'
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'

jobs:
  call-docker-build:
    name: Vote Call Docker Build

    uses: dockersamples/.github/.github/workflows/reusable-docker-build.yaml@main

    permissions:
      contents: read
      packages: write       # for GitHub Container Registry (ghcr.io)
      pull-requests: write  # to post comments on PRs

    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

    with:
      dockerhub-enable: false
      ghcr-enable: true

      image-names: |
        ghcr.io/<your-github-username>/example-voting-app-vote
        <your-dockerhub-username>/examplevotingapp_vote

      tag-rules: |
        type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=ref,event=pr

      context: vote
      platforms: linux/amd64,linux/arm64
